# Generated by Django 4.0.2 on 2022-03-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='status',
        ),
        migrations.AddField(
            model_name='produit',
            name='price',
            field=models.IntegerField(default='0', verbose_name='Produit price'),
        ),
        migrations.AddField(
            model_name='produit',
            name='quantity',
            field=models.IntegerField(default='0', verbose_name='Produit quantity'),
        ),
    ]
