# Generated by Django 4.0.2 on 2022-03-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_remove_produit_status_produit_price_produit_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.URLField(default='https://www.datocms-assets.com/45470/1631795624-logo-django.png', verbose_name='Produit image, url'),
        ),
    ]
